# Generated by Django 4.2 on 2025-12-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_banner_appuser_is_staff_alter_address_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
