# Generated by Django 4.2 on 2025-12-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_cartitem_options_cart_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="cart",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="added_at",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="price_at_addition",
        ),
    ]
