# Generated by Django 4.1.13 on 2025-12-06 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_conversation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('product', 'Product Share')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='api.product'),
        ),
        migrations.CreateModel(
            name='ProductShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.product')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to='api.appuser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_products', to='api.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productshare',
            index=models.Index(fields=['recipient', '-created_at'], name='api_product_recipie_749b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='productshare',
            index=models.Index(fields=['sender'], name='api_product_sender__20809d_idx'),
        ),
        migrations.AddIndex(
            model_name='productshare',
            index=models.Index(fields=['product'], name='api_product_product_14f80b_idx'),
        ),
    ]
