# Generated by Django 4.2 on 2025-12-07 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_cartitem_options_and_more"),
        ("api", "0009_message_message_type_message_shared_product_and_more"),
    ]

    operations = []
