# Generated by Django 4.2 on 2025-12-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_allergies_and_ingredients"),
        ("api", "0010_merge_20251207_0535"),
    ]

    operations = []
