# Generated by Django 4.2 on 2025-12-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_merge_20251207_0737"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
            },
        ),
        migrations.RemoveField(
            model_name="banner",
            name="link",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="position",
        ),
        migrations.AddField(
            model_name="banner",
            name="banner_type",
            field=models.CharField(
                choices=[
                    ("hero", "Hero Banner"),
                    ("featured", "Featured Products Banner"),
                    ("category", "Category Banner"),
                    ("promotional", "Promotional Banner"),
                ],
                default="featured",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="link_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="banner",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Display order (lower numbers appear first)"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
