# Generated by Django 4.2 on 2025-12-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_order_options_remove_booking_cashback_earned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
    ]
